<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('clients')->insert([
            [
                'name' => 'Nepal Life Insurance',
                'code' => 'NLI001',
                'mobile' => '9801234567',
                'land_line' => '01-4412345',
                'province_id' => 3,
                'district_id' => 17, // Kathmandu
                'city_id' => 101, // Kathmandu Metropolitan City
                'address' => 'Naxal, Kathmandu',
                'email' => 'info@nli.com',
                'contact_person' => 'Rajesh Sharma',
                'contact_person_contact' => '9801111222',
                'extra' => 'Major insurance provider in Nepal',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shikhar Insurance',
                'code' => 'SI002',
                'mobile' => '9807654321',
                'land_line' => '01-4432109',
                'province_id' => 3,
                'district_id' => 17,
                'city_id' => 102,
                'address' => 'Thamel, Kathmandu',
                'email' => 'contact@shikhar.com',
                'contact_person' => 'Suman Gautam',
                'contact_person_contact' => '9803334444',
                'extra' => 'Focused on health insurance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sagarmatha Insurance',
                'code' => 'SI003',
                'mobile' => '9802345678',
                'land_line' => '01-4487654',
                'province_id' => 1,
                'district_id' => 1,
                'city_id' => 201,
                'address' => 'Biratnagar, Morang',
                'email' => 'info@sagarmatha.com',
                'contact_person' => 'Maya Thapa',
                'contact_person_contact' => '9805556666',
                'extra' => 'Regional insurance company',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Everest Life',
                'code' => 'EL004',
                'mobile' => '9803456789',
                'land_line' => '01-4477123',
                'province_id' => 2,
                'district_id' => 35,
                'city_id' => 202,
                'address' => 'Janakpur, Dhanusha',
                'email' => 'contact@everestlife.com',
                'contact_person' => 'Ramesh Yadav',
                'contact_person_contact' => '9856789123',
                'extra' => 'Focused on student and family plans',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Gurkha Insurance',
                'code' => 'GI005',
                'mobile' => '9804567890',
                'land_line' => '01-4498765',
                'province_id' => 4,
                'district_id' => 48,
                'city_id' => 203,
                'address' => 'Lakeside, Pokhara',
                'email' => 'info@gurkha.com',
                'contact_person' => 'Sara Gurung',
                'contact_person_contact' => '9823456789',
                'extra' => 'Tourist insurance specialist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Lumbini Insurance',
                'code' => 'LI006',
                'mobile' => '9805678901',
                'land_line' => '071-545678',
                'province_id' => 5,
                'district_id' => 54,
                'city_id' => 204,
                'address' => 'Butwal, Rupandehi',
                'email' => 'contact@lumbini.com',
                'contact_person' => 'Bikash Khadka',
                'contact_person_contact' => '9867890123',
                'extra' => 'Corporate and staff insurance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Koshi Insurance',
                'code' => 'KI007',
                'mobile' => '9806789012',
                'land_line' => '026-441234',
                'province_id' => 1,
                'district_id' => 9,
                'city_id' => 205,
                'address' => 'Birgunj, Parsa',
                'email' => 'info@koshi.com',
                'contact_person' => 'Sita Sharma',
                'contact_person_contact' => '9807890123',
                'extra' => 'Health and accident insurance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Annapurna Insurance',
                'code' => 'AI008',
                'mobile' => '9807890123',
                'land_line' => '061-543210',
                'province_id' => 4,
                'district_id' => 48,
                'city_id' => 206,
                'address' => 'Pokhara, Lakeside',
                'email' => 'contact@annapurna.com',
                'contact_person' => 'Kiran Magar',
                'contact_person_contact' => '9801230987',
                'extra' => 'Life and travel insurance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mahendra Insurance',
                'code' => 'MI009',
                'mobile' => '9808901234',
                'land_line' => '01-4490123',
                'province_id' => 3,
                'district_id' => 17,
                'city_id' => 207,
                'address' => 'Koteshwor, Kathmandu',
                'email' => 'info@mahendra.com',
                'contact_person' => 'Suman Gautam',
                'contact_person_contact' => '9803456789',
                'extra' => 'Corporate insurance provider',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sagarmatha Life',
                'code' => 'SL010',
                'mobile' => '9809012345',
                'land_line' => '01-4410987',
                'province_id' => 3,
                'district_id' => 17,
                'city_id' => 208,
                'address' => 'Thapathali, Kathmandu',
                'email' => 'contact@sagarmathalife.com',
                'contact_person' => 'Maya Thapa',
                'contact_person_contact' => '9804567890',
                'extra' => 'Family insurance specialist',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
