<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'client_id' => 1,
                'user_id' => 1,
                'date_of_birth_bs' => '2055-04-15',
                'date_of_birth_ad' => '1998-07-29',
                'marital_status' => 'married',
                'gender' => 'male',
                'perm_province' => 1,
                'perm_district' => 1,
                'perm_city' => 1,
                'perm_ward_no' => 5,
                'perm_street' => 'New Baneshwor',
                'perm_house_no' => '123',
                'is_address_same' => 'Y',
                'present_province' => null,
                'present_district' => null,
                'present_city' => null,
                'present_ward_no' => null,
                'present_street' => null,
                'present_house_no' => null,
                'mail_address' => null,
                'phone_number' => '014567890',
                'employee_id' => 'EMP001',
                'branch' => 'Kathmandu Branch',
                'designation' => 'Senior Officer',
                'date_of_join' => '2023-01-15',
                'mobile_number' => 9841234567,
                'email' => 'rajesh.sharma@company.com',
                'nationality' => 'Nepali',
                'is_active' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'client_id' => 1,
                'user_id' => 3,
                'date_of_birth_bs' => '2058-11-22',
                'date_of_birth_ad' => '2002-03-06',
                'marital_status' => 'single',
                'gender' => 'female',
                'perm_province' => 3,
                'perm_district' => 1,
                'perm_city' => 1,
                'perm_ward_no' => 8,
                'perm_street' => 'Thapathali',
                'perm_house_no' => '456',
                'is_address_same' => 'N',
                'present_province' => 3,
                'present_district' => 10,
                'present_city' => 58,
                'present_ward_no' => 12,
                'present_street' => 'Jawalakhel',
                'present_house_no' => '789',
                'mail_address' => 'sanima.shrestha@gmail.com',
                'phone_number' => '015543210',
                'employee_id' => 'EMP002',
                'branch' => 'Lalitpur Branch',
                'designation' => 'Assistant Manager',
                'date_of_join' => '2023-06-01',
                'mobile_number' => 9876543210,
                'email' => 'sanima.shrestha@company.com',
                'nationality' => 'Nepali',
                'is_active' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'client_id' => 1,
                'user_id' => 4,
                'date_of_birth_bs' => '2050-08-10',
                'date_of_birth_ad' => '1993-11-24',
                'marital_status' => 'married',
                'gender' => 'male',
                'perm_province' => 1,
                'perm_district' => 35,
                'perm_city' => 200,
                'perm_ward_no' => 3,
                'perm_street' => 'Bhanu Chowk',
                'perm_house_no' => '101',
                'is_address_same' => 'Y',
                'present_province' => null,
                'present_district' => null,
                'present_city' => null,
                'present_ward_no' => null,
                'present_street' => null,
                'present_house_no' => null,
                'mail_address' => null,
                'phone_number' => '041540123',
                'employee_id' => 'EMP003',
                'branch' => 'Janakpur Branch',
                'designation' => 'Branch Manager',
                'date_of_join' => '2022-03-10',
                'mobile_number' => 9856789123,
                'email' => 'ramesh.yadav@company.com',
                'nationality' => 'Nepali',
                'is_active' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'client_id' => 1,
                'user_id' => 5,
                'date_of_birth_bs' => '2056-02-28',
                'date_of_birth_ad' => '1999-06-11',
                'marital_status' => 'single',
                'gender' => 'female',
                'perm_province' => 4,
                'perm_district' => 48,
                'perm_city' => 300,
                'perm_ward_no' => 15,
                'perm_street' => 'Lakeside',
                'perm_house_no' => '202',
                'is_address_same' => 'Y',
                'present_province' => null,
                'present_district' => null,
                'present_city' => null,
                'present_ward_no' => null,
                'present_street' => null,
                'present_house_no' => null,
                'mail_address' => null,
                'phone_number' => '061520123',
                'employee_id' => 'EMP004',
                'branch' => 'Pokhara Branch',
                'designation' => 'Executive',
                'date_of_join' => '2023-09-01',
                'mobile_number' => 9823456789,
                'email' => 'sara.gurung@company.com',
                'nationality' => 'Nepali',
                'is_active' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'client_id' => 3,
                'user_id' => 6,
                'date_of_birth_bs' => '2052-12-05',
                'date_of_birth_ad' => '1996-03-18',
                'marital_status' => 'married',
                'gender' => 'male',
                'perm_province' => 5,
                'perm_district' => 54,
                'perm_city' => 350,
                'perm_ward_no' => 7,
                'perm_street' => 'Traffic Chowk',
                'perm_house_no' => '303',
                'is_address_same' => 'Y',
                'present_province' => null,
                'present_district' => null,
                'present_city' => null,
                'present_ward_no' => null,
                'present_street' => null,
                'present_house_no' => null,
                'mail_address' => null,
                'phone_number' => '071540456',
                'employee_id' => 'EMP005',
                'branch' => 'Butwal Branch',
                'designation' => 'Senior Executive',
                'date_of_join' => '2022-11-15',
                'mobile_number' => 9867890123,
                'email' => 'bikash.khadka@company.com',
                'nationality' => 'Nepali',
                'is_active' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('members')->insert($members);
    }
}
